// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mul1,hls_ip_2018_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a12tcsg325-1q,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.470000,HLS_SYN_LAT=46,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=30,HLS_SYN_FF=764,HLS_SYN_LUT=879,HLS_VERSION=2018_2}" *)

module mul1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_we0,
        A_d0,
        A_q0,
        A_address1,
        A_ce1,
        A_we1,
        A_d1,
        A_q1,
        B_0_address0,
        B_0_ce0,
        B_0_q0,
        B_1_address0,
        B_1_ce0,
        B_1_q0,
        B_2_address0,
        B_2_ce0,
        B_2_q0,
        B_3_address0,
        B_3_ce0,
        B_3_q0,
        B_4_address0,
        B_4_ce0,
        B_4_q0,
        B_5_address0,
        B_5_ce0,
        B_5_q0,
        B_6_address0,
        B_6_ce0,
        B_6_q0,
        B_7_address0,
        B_7_ce0,
        B_7_q0,
        B_8_address0,
        B_8_ce0,
        B_8_q0,
        B_9_address0,
        B_9_ce0,
        B_9_q0,
        C_0_address0,
        C_0_ce0,
        C_0_we0,
        C_0_d0,
        C_0_q0,
        C_1_address0,
        C_1_ce0,
        C_1_we0,
        C_1_d0,
        C_1_q0,
        C_2_address0,
        C_2_ce0,
        C_2_we0,
        C_2_d0,
        C_2_q0,
        C_3_address0,
        C_3_ce0,
        C_3_we0,
        C_3_d0,
        C_3_q0,
        C_4_address0,
        C_4_ce0,
        C_4_we0,
        C_4_d0,
        C_4_q0,
        C_5_address0,
        C_5_ce0,
        C_5_we0,
        C_5_d0,
        C_5_q0,
        C_6_address0,
        C_6_ce0,
        C_6_we0,
        C_6_d0,
        C_6_q0,
        C_7_address0,
        C_7_ce0,
        C_7_we0,
        C_7_d0,
        C_7_q0,
        C_8_address0,
        C_8_ce0,
        C_8_we0,
        C_8_d0,
        C_8_q0,
        C_9_address0,
        C_9_ce0,
        C_9_we0,
        C_9_d0,
        C_9_q0,
        sparse_new_address0,
        sparse_new_ce0,
        sparse_new_q0,
        sparse_new_address1,
        sparse_new_ce1,
        sparse_new_q1
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] A_address0;
output   A_ce0;
output   A_we0;
output  [31:0] A_d0;
input  [31:0] A_q0;
output  [6:0] A_address1;
output   A_ce1;
output   A_we1;
output  [31:0] A_d1;
input  [31:0] A_q1;
output  [3:0] B_0_address0;
output   B_0_ce0;
input  [31:0] B_0_q0;
output  [3:0] B_1_address0;
output   B_1_ce0;
input  [31:0] B_1_q0;
output  [3:0] B_2_address0;
output   B_2_ce0;
input  [31:0] B_2_q0;
output  [3:0] B_3_address0;
output   B_3_ce0;
input  [31:0] B_3_q0;
output  [3:0] B_4_address0;
output   B_4_ce0;
input  [31:0] B_4_q0;
output  [3:0] B_5_address0;
output   B_5_ce0;
input  [31:0] B_5_q0;
output  [3:0] B_6_address0;
output   B_6_ce0;
input  [31:0] B_6_q0;
output  [3:0] B_7_address0;
output   B_7_ce0;
input  [31:0] B_7_q0;
output  [3:0] B_8_address0;
output   B_8_ce0;
input  [31:0] B_8_q0;
output  [3:0] B_9_address0;
output   B_9_ce0;
input  [31:0] B_9_q0;
output  [3:0] C_0_address0;
output   C_0_ce0;
output   C_0_we0;
output  [31:0] C_0_d0;
input  [31:0] C_0_q0;
output  [3:0] C_1_address0;
output   C_1_ce0;
output   C_1_we0;
output  [31:0] C_1_d0;
input  [31:0] C_1_q0;
output  [3:0] C_2_address0;
output   C_2_ce0;
output   C_2_we0;
output  [31:0] C_2_d0;
input  [31:0] C_2_q0;
output  [3:0] C_3_address0;
output   C_3_ce0;
output   C_3_we0;
output  [31:0] C_3_d0;
input  [31:0] C_3_q0;
output  [3:0] C_4_address0;
output   C_4_ce0;
output   C_4_we0;
output  [31:0] C_4_d0;
input  [31:0] C_4_q0;
output  [3:0] C_5_address0;
output   C_5_ce0;
output   C_5_we0;
output  [31:0] C_5_d0;
input  [31:0] C_5_q0;
output  [3:0] C_6_address0;
output   C_6_ce0;
output   C_6_we0;
output  [31:0] C_6_d0;
input  [31:0] C_6_q0;
output  [3:0] C_7_address0;
output   C_7_ce0;
output   C_7_we0;
output  [31:0] C_7_d0;
input  [31:0] C_7_q0;
output  [3:0] C_8_address0;
output   C_8_ce0;
output   C_8_we0;
output  [31:0] C_8_d0;
input  [31:0] C_8_q0;
output  [3:0] C_9_address0;
output   C_9_ce0;
output   C_9_we0;
output  [31:0] C_9_d0;
input  [31:0] C_9_q0;
output  [4:0] sparse_new_address0;
output   sparse_new_ce0;
input  [31:0] sparse_new_q0;
output  [4:0] sparse_new_address1;
output   sparse_new_ce1;
input  [31:0] sparse_new_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg B_0_ce0;
reg B_1_ce0;
reg B_2_ce0;
reg B_3_ce0;
reg B_4_ce0;
reg B_5_ce0;
reg B_6_ce0;
reg B_7_ce0;
reg B_8_ce0;
reg B_9_ce0;
reg[3:0] C_0_address0;
reg C_0_ce0;
reg C_0_we0;
reg[3:0] C_1_address0;
reg C_1_ce0;
reg C_1_we0;
reg[3:0] C_2_address0;
reg C_2_ce0;
reg C_2_we0;
reg[3:0] C_3_address0;
reg C_3_ce0;
reg C_3_we0;
reg[3:0] C_4_address0;
reg C_4_ce0;
reg C_4_we0;
reg[3:0] C_5_address0;
reg C_5_ce0;
reg C_5_we0;
reg[3:0] C_6_address0;
reg C_6_ce0;
reg C_6_we0;
reg[3:0] C_7_address0;
reg C_7_ce0;
reg C_7_we0;
reg[3:0] C_8_address0;
reg C_8_ce0;
reg C_8_we0;
reg[3:0] C_9_address0;
reg C_9_ce0;
reg C_9_we0;
reg[4:0] sparse_new_address0;
reg sparse_new_ce0;
reg sparse_new_ce1;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] i_1_fu_380_p2;
reg   [3:0] i_1_reg_560;
wire    ap_CS_fsm_state2;
wire  signed [5:0] tmp_4_fu_398_p2;
reg  signed [5:0] tmp_4_reg_565;
wire   [0:0] exitcond1_fu_374_p2;
wire    ap_CS_fsm_state3;
reg   [31:0] r_reg_585;
reg  signed [31:0] val_reg_640;
wire    ap_CS_fsm_state4;
reg  signed [31:0] B_0_load_reg_654;
reg  signed [31:0] B_1_load_reg_659;
reg  signed [31:0] B_2_load_reg_664;
reg  signed [31:0] B_3_load_reg_669;
reg  signed [31:0] B_4_load_reg_674;
reg  signed [31:0] B_5_load_reg_679;
reg  signed [31:0] B_6_load_reg_684;
reg  signed [31:0] B_7_load_reg_689;
reg  signed [31:0] B_8_load_reg_694;
reg  signed [31:0] B_9_load_reg_699;
wire   [31:0] tmp_5_fu_457_p2;
reg   [31:0] tmp_5_reg_704;
wire    ap_CS_fsm_state5;
reg   [3:0] C_0_addr_reg_709;
wire   [31:0] tmp_5_1_fu_461_p2;
reg   [31:0] tmp_5_1_reg_714;
reg   [3:0] C_1_addr_reg_719;
wire   [31:0] tmp_5_2_fu_465_p2;
reg   [31:0] tmp_5_2_reg_724;
reg   [3:0] C_2_addr_reg_729;
wire   [31:0] tmp_5_3_fu_469_p2;
reg   [31:0] tmp_5_3_reg_734;
reg   [3:0] C_3_addr_reg_739;
wire   [31:0] tmp_5_4_fu_473_p2;
reg   [31:0] tmp_5_4_reg_744;
reg   [3:0] C_4_addr_reg_749;
wire   [31:0] tmp_5_5_fu_477_p2;
reg   [31:0] tmp_5_5_reg_754;
reg   [3:0] C_5_addr_reg_759;
wire   [31:0] tmp_5_6_fu_481_p2;
reg   [31:0] tmp_5_6_reg_764;
reg   [3:0] C_6_addr_reg_769;
wire   [31:0] tmp_5_7_fu_485_p2;
reg   [31:0] tmp_5_7_reg_774;
reg   [3:0] C_7_addr_reg_779;
wire   [31:0] tmp_5_8_fu_489_p2;
reg   [31:0] tmp_5_8_reg_784;
reg   [3:0] C_8_addr_reg_789;
wire   [31:0] tmp_5_9_fu_493_p2;
reg   [31:0] tmp_5_9_reg_794;
reg   [3:0] C_9_addr_reg_799;
reg   [3:0] i_reg_363;
wire    ap_CS_fsm_state6;
wire  signed [63:0] tmp_4_cast_fu_404_p1;
wire  signed [63:0] tmp_7_cast_fu_415_p1;
wire  signed [63:0] tmp_8_cast_fu_425_p1;
wire  signed [63:0] tmp_1_fu_430_p1;
wire  signed [63:0] tmp_2_fu_444_p1;
wire   [5:0] tmp_3_fu_390_p3;
wire   [5:0] tmp_cast_fu_386_p1;
wire   [5:0] tmp_7_fu_409_p2;
wire   [5:0] tmp_8_fu_420_p2;
reg   [5:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        i_reg_363 <= i_1_reg_560;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_363 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        B_0_load_reg_654 <= B_0_q0;
        B_1_load_reg_659 <= B_1_q0;
        B_2_load_reg_664 <= B_2_q0;
        B_3_load_reg_669 <= B_3_q0;
        B_4_load_reg_674 <= B_4_q0;
        B_5_load_reg_679 <= B_5_q0;
        B_6_load_reg_684 <= B_6_q0;
        B_7_load_reg_689 <= B_7_q0;
        B_8_load_reg_694 <= B_8_q0;
        B_9_load_reg_699 <= B_9_q0;
        val_reg_640 <= sparse_new_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        C_0_addr_reg_709 <= tmp_2_fu_444_p1;
        C_1_addr_reg_719 <= tmp_2_fu_444_p1;
        C_2_addr_reg_729 <= tmp_2_fu_444_p1;
        C_3_addr_reg_739 <= tmp_2_fu_444_p1;
        C_4_addr_reg_749 <= tmp_2_fu_444_p1;
        C_5_addr_reg_759 <= tmp_2_fu_444_p1;
        C_6_addr_reg_769 <= tmp_2_fu_444_p1;
        C_7_addr_reg_779 <= tmp_2_fu_444_p1;
        C_8_addr_reg_789 <= tmp_2_fu_444_p1;
        C_9_addr_reg_799 <= tmp_2_fu_444_p1;
        tmp_5_1_reg_714 <= tmp_5_1_fu_461_p2;
        tmp_5_2_reg_724 <= tmp_5_2_fu_465_p2;
        tmp_5_3_reg_734 <= tmp_5_3_fu_469_p2;
        tmp_5_4_reg_744 <= tmp_5_4_fu_473_p2;
        tmp_5_5_reg_754 <= tmp_5_5_fu_477_p2;
        tmp_5_6_reg_764 <= tmp_5_6_fu_481_p2;
        tmp_5_7_reg_774 <= tmp_5_7_fu_485_p2;
        tmp_5_8_reg_784 <= tmp_5_8_fu_489_p2;
        tmp_5_9_reg_794 <= tmp_5_9_fu_493_p2;
        tmp_5_reg_704 <= tmp_5_fu_457_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_1_reg_560 <= i_1_fu_380_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        r_reg_585 <= sparse_new_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond1_fu_374_p2 == 1'd0))) begin
        tmp_4_reg_565 <= tmp_4_fu_398_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        B_0_ce0 = 1'b1;
    end else begin
        B_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        B_1_ce0 = 1'b1;
    end else begin
        B_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        B_2_ce0 = 1'b1;
    end else begin
        B_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        B_3_ce0 = 1'b1;
    end else begin
        B_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        B_4_ce0 = 1'b1;
    end else begin
        B_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        B_5_ce0 = 1'b1;
    end else begin
        B_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        B_6_ce0 = 1'b1;
    end else begin
        B_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        B_7_ce0 = 1'b1;
    end else begin
        B_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        B_8_ce0 = 1'b1;
    end else begin
        B_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        B_9_ce0 = 1'b1;
    end else begin
        B_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_0_address0 = C_0_addr_reg_709;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        C_0_address0 = tmp_2_fu_444_p1;
    end else begin
        C_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        C_0_ce0 = 1'b1;
    end else begin
        C_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_0_we0 = 1'b1;
    end else begin
        C_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_1_address0 = C_1_addr_reg_719;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        C_1_address0 = tmp_2_fu_444_p1;
    end else begin
        C_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        C_1_ce0 = 1'b1;
    end else begin
        C_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_1_we0 = 1'b1;
    end else begin
        C_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_2_address0 = C_2_addr_reg_729;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        C_2_address0 = tmp_2_fu_444_p1;
    end else begin
        C_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        C_2_ce0 = 1'b1;
    end else begin
        C_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_2_we0 = 1'b1;
    end else begin
        C_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_3_address0 = C_3_addr_reg_739;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        C_3_address0 = tmp_2_fu_444_p1;
    end else begin
        C_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        C_3_ce0 = 1'b1;
    end else begin
        C_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_3_we0 = 1'b1;
    end else begin
        C_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_4_address0 = C_4_addr_reg_749;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        C_4_address0 = tmp_2_fu_444_p1;
    end else begin
        C_4_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        C_4_ce0 = 1'b1;
    end else begin
        C_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_4_we0 = 1'b1;
    end else begin
        C_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_5_address0 = C_5_addr_reg_759;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        C_5_address0 = tmp_2_fu_444_p1;
    end else begin
        C_5_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        C_5_ce0 = 1'b1;
    end else begin
        C_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_5_we0 = 1'b1;
    end else begin
        C_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_6_address0 = C_6_addr_reg_769;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        C_6_address0 = tmp_2_fu_444_p1;
    end else begin
        C_6_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        C_6_ce0 = 1'b1;
    end else begin
        C_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_6_we0 = 1'b1;
    end else begin
        C_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_7_address0 = C_7_addr_reg_779;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        C_7_address0 = tmp_2_fu_444_p1;
    end else begin
        C_7_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        C_7_ce0 = 1'b1;
    end else begin
        C_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_7_we0 = 1'b1;
    end else begin
        C_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_8_address0 = C_8_addr_reg_789;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        C_8_address0 = tmp_2_fu_444_p1;
    end else begin
        C_8_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        C_8_ce0 = 1'b1;
    end else begin
        C_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_8_we0 = 1'b1;
    end else begin
        C_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_9_address0 = C_9_addr_reg_799;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        C_9_address0 = tmp_2_fu_444_p1;
    end else begin
        C_9_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        C_9_ce0 = 1'b1;
    end else begin
        C_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        C_9_we0 = 1'b1;
    end else begin
        C_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond1_fu_374_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond1_fu_374_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sparse_new_address0 = tmp_8_cast_fu_425_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sparse_new_address0 = tmp_4_cast_fu_404_p1;
    end else begin
        sparse_new_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        sparse_new_ce0 = 1'b1;
    end else begin
        sparse_new_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        sparse_new_ce1 = 1'b1;
    end else begin
        sparse_new_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (exitcond1_fu_374_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = 7'd0;

assign A_address1 = 7'd0;

assign A_ce0 = 1'b0;

assign A_ce1 = 1'b0;

assign A_d0 = 32'd0;

assign A_d1 = 32'd0;

assign A_we0 = 1'b0;

assign A_we1 = 1'b0;

assign B_0_address0 = tmp_1_fu_430_p1;

assign B_1_address0 = tmp_1_fu_430_p1;

assign B_2_address0 = tmp_1_fu_430_p1;

assign B_3_address0 = tmp_1_fu_430_p1;

assign B_4_address0 = tmp_1_fu_430_p1;

assign B_5_address0 = tmp_1_fu_430_p1;

assign B_6_address0 = tmp_1_fu_430_p1;

assign B_7_address0 = tmp_1_fu_430_p1;

assign B_8_address0 = tmp_1_fu_430_p1;

assign B_9_address0 = tmp_1_fu_430_p1;

assign C_0_d0 = (tmp_5_reg_704 + C_0_q0);

assign C_1_d0 = (tmp_5_1_reg_714 + C_1_q0);

assign C_2_d0 = (tmp_5_2_reg_724 + C_2_q0);

assign C_3_d0 = (tmp_5_3_reg_734 + C_3_q0);

assign C_4_d0 = (tmp_5_4_reg_744 + C_4_q0);

assign C_5_d0 = (tmp_5_5_reg_754 + C_5_q0);

assign C_6_d0 = (tmp_5_6_reg_764 + C_6_q0);

assign C_7_d0 = (tmp_5_7_reg_774 + C_7_q0);

assign C_8_d0 = (tmp_5_8_reg_784 + C_8_q0);

assign C_9_d0 = (tmp_5_9_reg_794 + C_9_q0);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign exitcond1_fu_374_p2 = ((i_reg_363 == 4'd9) ? 1'b1 : 1'b0);

assign i_1_fu_380_p2 = (i_reg_363 + 4'd1);

assign sparse_new_address1 = tmp_7_cast_fu_415_p1;

assign tmp_1_fu_430_p1 = $signed(sparse_new_q1);

assign tmp_2_fu_444_p1 = $signed(r_reg_585);

assign tmp_3_fu_390_p3 = {{i_reg_363}, {2'd0}};

assign tmp_4_cast_fu_404_p1 = tmp_4_fu_398_p2;

assign tmp_4_fu_398_p2 = (tmp_3_fu_390_p3 - tmp_cast_fu_386_p1);

assign tmp_5_1_fu_461_p2 = ($signed(B_1_load_reg_659) * $signed(val_reg_640));

assign tmp_5_2_fu_465_p2 = ($signed(B_2_load_reg_664) * $signed(val_reg_640));

assign tmp_5_3_fu_469_p2 = ($signed(B_3_load_reg_669) * $signed(val_reg_640));

assign tmp_5_4_fu_473_p2 = ($signed(B_4_load_reg_674) * $signed(val_reg_640));

assign tmp_5_5_fu_477_p2 = ($signed(B_5_load_reg_679) * $signed(val_reg_640));

assign tmp_5_6_fu_481_p2 = ($signed(B_6_load_reg_684) * $signed(val_reg_640));

assign tmp_5_7_fu_485_p2 = ($signed(B_7_load_reg_689) * $signed(val_reg_640));

assign tmp_5_8_fu_489_p2 = ($signed(B_8_load_reg_694) * $signed(val_reg_640));

assign tmp_5_9_fu_493_p2 = ($signed(B_9_load_reg_699) * $signed(val_reg_640));

assign tmp_5_fu_457_p2 = ($signed(B_0_load_reg_654) * $signed(val_reg_640));

assign tmp_7_cast_fu_415_p1 = $signed(tmp_7_fu_409_p2);

assign tmp_7_fu_409_p2 = ($signed(tmp_4_fu_398_p2) + $signed(6'd1));

assign tmp_8_cast_fu_425_p1 = $signed(tmp_8_fu_420_p2);

assign tmp_8_fu_420_p2 = ($signed(tmp_4_reg_565) + $signed(6'd2));

assign tmp_cast_fu_386_p1 = i_reg_363;

endmodule //mul1
